### ISSUE TITLE
FlxSprites nested in FlxGroups do not call postUpdate()

### ISSUE THREAD

**Issue by benzido** [AdamAtomic/flixel#149]
If I have a subclass of FlxGroup with a FlxSprite member, postUpdate is not called per frame on the FlxSprite unless it is manually called from within the FlxGroup's update function. This means that baked rotation doesn't work in this situation, although regular rotation does.

**Comment by AdamAtomic** [comment]
yea, you can also override flxgroup's postUpdate() function, and call super.postUpdate() followed by myMemberSprite.postUpdate() (and do the same for preUpdate()).  Otherwise you do have to do it by hand, or else actually add the FlxSprite to the group's member array where it will happen automatically
