### ISSUE TITLE
Sound glitch when unpausing

### ISSUE THREAD

**Issue by noidexe** [AdamAtomic/flixel#159]
It started happening with the latest commits, probably since AdamAtomic@147f95a6ca526801976e

When you pause the game and then unpause it, all the sounds ever played with FlxG.play() play at once. 

It also happens with buttons if you set soundOver with setSounds() and in that case the soundOver sound plays even if it never played before pausing the game.

It doesn't happen with any FlxSound played through mySound.play(), only when using FlxG.play();

**Comment by AdamAtomic** [comment]
yeaaaa that kind of maybe makes sense... hmmm.  i'll check it out, should have a fix up soon!

**Comment by AdamAtomic** [comment]
ok making a bit of headway... if you're manually loading sounds and you are expecting them to disappear like they used to, you're going to want to set the AutoDestroy parameter in loadEmbedded() or loadStream() to "true".  FlxG.play() does this already, but you'll definitely want to do that in your own sound handlers (IF that is in fact the behavior you want).  The reason for this is you can now choose to keep sounds around even though they're part of the FlxG sound stack, meaning you can conserve memory/keep control of the sounds, AND keep them in the globa sound system, which is nice.  Eventually the sound ssystem will be more like FlxTimer, a plug-in based thing, but I haven't gotten that far yet...

i updated FlxG and FlxGame to use pauseSounds() and resumeSounds() instead of pauseSounds() and playSounds(), and removed playSounds() entirely.  resumeSounds() uses a new, specialized version of FlxSound.play() called FlxSound.resume(), which will only play sounds that were actually paused.
