### ISSUE TITLE
FlxG.flash and FlxG.fade receiving the wrong color

### ISSUE THREAD

**Issue by Markham** [AdamAtomic/flixel#4]
For some reason, when calling one after the other, the color for the last one is applied to both.

IE:
FlxG.flash(0xffffffff,0.5);
FlxG.fade(0xff000000,1,function);
The screen flashes black, and then fades to black.

FlxG.fade(0xff000000,1,function);
FlxG.flash(0xffffffff,0.5);
The screen flashes white, and then fades to white.

**Comment by fefranca** [comment]
I am 99% sure this is due to FlxFade and FlxFlash sharing the same BitmapData object, due to the caching done inside the FlxG.createBitmap method.

You can most likely temporarely fix this by changing this line in the FlxFade constructor: (just make sure the Color value is different between FlxFade and FlxFlash)

super(null,0,0,false,false,FlxG.width,FlxG.height);

To:
super(null,0,0,false,false,FlxG.width,FlxG.height,0xfffffffe);

This will force Flixel to use a different BitmapData.

**Comment by AdamAtomic** [comment]
Actually flxsprites have a unique flag now, this hsould be a 3 or 4 second fix, lemme see....

**Comment by AdamAtomic** [comment]
ok yea I flagged the buffers for those fx as unique, should go up in the next upload :)  nice catch!

**Comment by AdamAtomic** [comment]
Closing this, feel free to re-open if v1.32+ doesn't help!

**Comment by fefranca** [comment]
Great Adam, here is a little bugfix in FlxG.createBitmap's Unique code for your upcoming revision (ukey wasn't being used). Hope it saves you some time.

var ukey:String;
do { ukey = key + inc++; } while((_cache[ukey] != undefined) && (_cache[ukey] != null));
_cache[ukey] = new BitmapData(Width, Height, true, Color);

**Comment by AdamAtomic** [comment]
doh, good catch - I actually did it slightly differently than that in the fix but yea, I have no idea how that old code was even working sometimes o_O
