### ISSUE TITLE
FlxObject.hitRight() calls FlxObject.hitLeft(), causing unexpected behavior when overriding

### ISSUE THREAD

**Issue by prionicjive** [AdamAtomic/flixel#54]
Looking at FlxObject in v2.23, you'll see that hitRight() calls hitLeft() to update velocity. This is fine if you never override either, but if you do, these calls could possibly lead to unexpected behavior.

I hadn't noticed anything until I put in some flags to be set only on hitLeft() and only on hitRight(). I saw the flags that were only supposed to be set on hitLeft() were also being set when the player object was only colliding with something to its right.

Explicitly putting the code from hitLeft() into hitRight() solved all of my problems, just thought this would be good to have in!

**Comment by AdamAtomic** [comment]
yea this was intentional, as (i think) most games usually only care if you hit a wall, not which wall you hit - so overriding just the one function is faster + easier for most people...I agree that it is kind of weird though.  Maybe they should both call a new function hitWall() instead?  Hrrm...  I will think about this for the dev branch!  I don't wanna do any API changes to the master branch unless absolutely necessary
