### ISSUE TITLE
[2.34] A typo in FlxU class

### ISSUE THREAD

**Issue by syndrome** [AdamAtomic/flixel#73]
Flixel v2.34, FlxU.as, line 139 contains the excess word 'retur' which doesn't produce an error or warning when compiled.

**Comment by BillyWM** [comment]
Someone on the forums today was reporting a problem with this throwing errors with FDT.

http://flixel.org/forums/index.php?topic=1741.0

Normally (say in mxmlc on the command-line) it's ignored because the function returns on the first line, but I guess some compilers throw errors. The other lines should be removed because they're non-functional anyway.

**Comment by AdamAtomic** [comment]
yea that function was pretty messed up, haha - was fixed a little while ago.  thanks tho!
