### ISSUE TITLE
[trunk] Important: hitLeft called on hitRight (w/solution)

### ISSUE THREAD

**Issue by ghost** [AdamAtomic/flixel#80]
Even if hitRight does the same for FlxObject as hitLeft the behaviour of it might change in a derived class, and calling hitLeft on hitRight will trigger the derived hitLeft that can have a different behaviour (e.g. For wall grabbing)

<pre>
public function hitRight(Contact:FlxObject,Velocity:Number):void
{
   hitLeft(Contact,Velocity);   //Error, derived class will get hitRight and on it's super.hitRight, a hitLeft
}
</pre>

A comment should be added to avoid repetition of the same error pattern.

Best regards
-Martín

**Comment by AdamAtomic** [comment]
i updated this so that hitLeft() and hitRight() both call a new function hitSide() by default, it should be less confusing!  You can override hitLeft() and hitRight() normally now, or just override hitSide() to do the same behavior for both - hopefully will help with weird inheritance problems...will go out on beta and dev tonight!

**Comment by ghost** [comment]
Cool!
