### ISSUE TITLE
Wierd Collision Problems

### ISSUE THREAD

**Issue by hamedn** [AdamAtomic/flixel#88]
Hey,

Your previous collision changes almost fixed this bug, but it still occurs in some situations. I have my player's FlxSprite with a acceleration.x = whatever positive number. Basically, the object's gravity is pushing it to the right. Next I have a bunch of 32x32 objects in a vertical line. When my player moves up the line, he can't cross over to the next object, but when moving downward, everything works fine. Take a look at the image below. Green means that he can move in that direction and put his foot on the block. Red means he stops at the edge of the block he is currently on:

http://i48.tinypic.com/1606k3c.png

NOTE: Please ignore those green arrows, they are part of the background!

**Comment by AdamAtomic** [comment]
Unless it's a tilemap, currently that is still an issue with the default way collisions are done in flixel.  HOWEVER you should be able to avoid it if instead of just using (in v2.50) FlxG.collide, you instead call FlxG.overlap() twice, with FlxObject.SeparateX() and FlxObject.SeparateY() respectively as your processing callbacks
