### ISSUE TITLE
FlxEmitter should handle changes in its members while emitting

### ISSUE THREAD

**Issue by NickLanam** [AdamAtomic/flixel#93]
As it stands, when a FlxEmitter has the length of its members Array changed while the FlxEmitter is emitting, a few things can happen:

If it was lengthened:

If the element gets push()ed to the end of the array, no harm done. emitParticle() will emit it when it reaches that point in the Array, unless it was already at the end of the Array and just reset, in which case the element won't get emitted until the next pass.
If the element was unshift()ed, emitParticle() will reemit the particle it just emitted on the next call of emitParticle() - usually harmless, but if there is a custom group of particles that needs to come out in a particular order, this is not desirable.
If it was shortened:

If the element was pop()ed, emitParticle() will either work just fine, not emitting that element, or, if it was just about to emit that element, there will be an error #1009 (null reference error). AKA, crash.
If the element was unshift()ed, the element that the emitter was about to emit gets skipped, or if the emitter is at the end of the premodification array, another #1009 results.

If it was changed with slice() or splice(), any combination of the above issues can result, depending on what exactly you did to it.

An improvement to this relatively new feature would be if FlxEmitter listened for changes to its members array (easy enough to do with getters and setters) and adjusted the _particle uint member accordingly. I am unsure, however, as to how to check _which_ element in the Array was changed, which is needed information to do this.

If I turn out to not be the only one who wants this improvement, I can make changes to my copy of FlxEmitter and see if I make any progress.

NOTE: A simple change that will prevent #1009's is below. When _particle exceeds the bounds of the members Array, it will reset _particle to 0. Add these after the line that reads "_counter++;" in emitParticle() and #1009's stop.

if (_particle >= members.length)
    _particle = 0;

**Comment by AdamAtomic** [comment]
so in v2.50 i made flxgroup much better/smarter about the way it recycles objects, and flxemitter uses that new system.  this system can be used with either a flexible group size or a fixed group size, and _hopefully_ it will take care of this problem.  that said, i have not tried heavily manipulating flash arrays from outside a group much, as they're rather bad performance.  that doesn't mean they shouldn't be used, but this problem MAY persist.  however, because of the architecture changes, its ahrd for me to say.  if this is still a problem let me know!
